server_name: jenkins-test-server
user_name: fmw
repositories:
  cob_navigation_intern:
    ros_distro: [groovy]
    robots: null
    jobs: []
    poll: true
    dependencies:
      cob_navigation: {poll: false, test: false, type: git, url: 'git@github.com:ipa320/cob_navigation.git',
        version: groovy_dev}
    prio_ubuntu_distro: precise
    regular_matrix: {}
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/cob_navigation_intern.git
    version: fuerte_dev
email: fmw@ipa.fhg.de
committer_email_enabled: false
