server_name: cob-jenkins-server
user_name: fmw
repositories:
  cob_extern:
    ros_distro: [groovy]
    robots: []
    jobs: []
    poll: true
    dependencies: {}
    matrix_distro_arch: {}
    prio_ubuntu_distro: precise
    prio_arch: amd64
    type: git
    url: git@github.com:abubeck/cob_extern.git
    version: feature/catkin
email: fmw@ipa.fhg.de
committer_email_enabled: false
