server_name: cob-jenkins-server
user_name: fmw
repositories:
  cob_driver__ipa320_catkin:
    ros_distro: [groovy]
    robots: []
    jobs: [regular_build]
    poll: true
    dependencies: {}
    matrix_distro_arch:
      oneiric: [amd64, i386]
      quantal: [amd64, i386]
      precise: [i386]
    prio_ubuntu_distro: precise
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/cob_driver.git
    version: groovy_catkin
  cob_extern__ipa320_catkin:
    ros_distro: [groovy]
    robots: []
    jobs: [regular_build]
    poll: true
    dependencies: {}
    matrix_distro_arch:
      oneiric: [amd64, i386]
      quantal: [amd64, i386]
      precise: [i386]
    prio_ubuntu_distro: precise
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/cob_extern.git
    version: groovy_catkin
  cob_common__ipa320_catkin:
    ros_distro: [groovy]
    robots: []
    jobs: [regular_build]
    poll: true
    dependencies: {}
    matrix_distro_arch:
      oneiric: [amd64, i386]
      quantal: [amd64, i386]
      precise: [i386]
    prio_ubuntu_distro: precise
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/cob_common.git
    version: groovy_catkin
email: fmw@ipa.fhg.de
committer_email_enabled: false
