server_name: cob-jenkins-server
user_name: fmw
repositories:
  industrial_core:
    ros_distro: [groovy]
    robots: null
    jobs: [regular_build, downstream_build, nongraphics_test]
    poll: true
    dependencies: {}
    prio_ubuntu_distro: precise
    regular_matrix:
      oneiric: [amd64, i386]
      quantal: [amd64, i386]
      precise: [i386]
    prio_arch: amd64
    type: git
    url: git@github.com:ros-industrial/industrial_core.git
    version: groovy-devel
email: fmw@ipa.fhg.de
committer_email_enabled: false
