server_name: fmw-xps
user_name: ipa-jenkins
repositories:
  cob_common:
    ros_distro: [groovy]
    robots: null
    jobs: []
    poll: true
    dependencies: {}
    prio_ubuntu_distro: oneiric
    regular_matrix: {}
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/cob_common.git
    version: groovy
email: jannik.kett@gmail.com
committer_email_enabled: false
