server_name: cob-jenkins-server
user_name: fmw-jk
repositories:
  cob_common__suffix:
    ros_distro: [electric]
    robots: []
    jobs: []
    poll: true
    dependencies: {}
    matrix_distro_arch: {}
    prio_ubuntu_distro: natty
    prio_arch: amd64
    type: git
    url: git@github.com:fmw-jk/cob_common.git
    version: master
  cob_extern:
    ros_distro: [fuerte]
    robots: []
    jobs: [regular_build]
    poll: true
    dependencies: {}
    matrix_distro_arch:
      oneiric: [i386]
    prio_ubuntu_distro: oneiric
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/cob_extern.git
    version: fuerte_release_candidate
email: jannik.kett@gmail.com
committer_email_enabled: false
