server_name: cob-jenkins-server
user_name: fmw-jk
repositories:
  cob_common__suffix:
    ros_distro: [electric]
    robots: []
    jobs: []
    poll: true
    dependencies: {}
    matrix_distro_arch: {}
    prio_ubuntu_distro: natty
    prio_arch: amd64
    type: git
    url: git@github.com:fmw-jk/cob_common.git
    version: master
email: jannik.kett@gmail.com
committer_email_enabled: false
