server_name: cob-jenkins-server
user_name: fmw-jk
repositories:
  cob_common__suffix:
    ros_distro: [electric]
    robots: []
    jobs: []
    poll: true
    dependencies: {}
    matrix_distro_arch: {}
    prio_ubuntu_distro: natty
    prio_arch: amd64
    type: git
    url: git@github.com:fmw-jk/cob_common.git
    version: master
  cob_navigation__fuerte:
    ros_distro: [fuerte]
    robots: []
    jobs: []
    poll: true
    dependencies: {}
    matrix_distro_arch: {}
    prio_ubuntu_distro: oneiric
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/cob_navigation.git
    version: fuerte
  cob_driver__fuerte:
    ros_distro: [fuerte]
    robots: []
    jobs: []
    poll: true
    dependencies: {}
    matrix_distro_arch: {}
    prio_ubuntu_distro: oneiric
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/cob_driver.git
    version: fuerte
  ros_tutorials:
    ros_distro: [groovy]
    robots: []
    jobs: []
    poll: true
    dependencies: {}
    matrix_distro_arch: {}
    prio_ubuntu_distro: oneiric
    prio_arch: amd64
    type: git
    url: git@github.com:ros/ros_tutorials.git
    version: groovy-devel
  cob_navigation:
    ros_distro: [electric]
    robots: []
    jobs: []
    poll: true
    dependencies: {}
    matrix_distro_arch: {}
    prio_ubuntu_distro: oneiric
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/cob_navigation.git
    version: electric
  cob_extern__groovy:
    ros_distro: [groovy]
    robots: []
    jobs: []
    poll: true
    dependencies: {}
    matrix_distro_arch: {}
    prio_ubuntu_distro: oneiric
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/cob_extern.git
    version: groovy_dev
  cob_driver:
    ros_distro: [electric]
    robots: []
    jobs: []
    poll: true
    dependencies: {}
    matrix_distro_arch: {}
    prio_ubuntu_distro: oneiric
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/cob_driver.git
    version: electric
  cob_extern:
    ros_distro: [electric]
    robots: []
    jobs: []
    poll: true
    dependencies: {}
    matrix_distro_arch: {}
    prio_ubuntu_distro: natty
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/cob_extern.git
    version: electric
  cob_robots:
    ros_distro: [electric]
    robots: []
    jobs: []
    poll: true
    dependencies: {}
    matrix_distro_arch: {}
    prio_ubuntu_distro: natty
    prio_arch: amd64
    type: git
    url: git@github.com:ipa-fmw/cob_robots.git
    version: master
email: jannik.kett@gmail.com
committer_email_enabled: false
