server_name: cob-jenkins-server
user_name: fmw-jk
repositories:
  cob_navigation:
    ros_distro: [groovy]
    robots: null
    jobs: [downstream_build, graphics_test]
    poll: true
    dependencies: {}
    prio_ubuntu_distro: oneiric
    regular_matrix: {}
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/cob_navigation.git
    version: groovy_dev
email: jannik.kett@gmail.com
committer_email_enabled: false
