server_name: cob-jenkins-server
user_name: goa
repositories:
  cob_environment_perception:
    ros_distro: [groovy]
    robots: []
    jobs: []
    poll: true
    dependencies:
      cob_perception_common: {poll: false, type: git, url: 'git@github.com:ipa320/cob_perception_common.git',
        version: electric_dev}
      cob_common: {poll: false, type: git, url: 'git@github.com:ipa320/cob_common.git',
        version: groovy_dev}
    matrix_distro_arch: {}
    prio_ubuntu_distro: oneiric
    prio_arch: amd64
    type: git
    url: git@github.com:ipa-goa/cob_environment_perception.git
    version: master
email: goa@ipa.fhg.de
committer_email_enabled: false
