user_name: fmw
server_name: fmw-xps
email: fmw@ipa.fhg.de
committer_email_enabled: false

repositories:
    test_repo_1:
        type: git  # git, hg, svn
        url: git@github.com/ipa-fmw/cob_robots
        version: electric_dev
        poll: true  # for first level repos always true
        ros_distro: [electric]  # electric, fuerte,...
        prio_ubuntu_distro: lucid
        prio_arch: amd64
        matrix_distro_arch:
            oneiric: [amd64]
            lucid: [amd64, i386]
        dependencies:
            dep_repo_1:
                type: git  # git, hg, svn
                url: git@github.com/ipa-fmw/cob_driver
                version: electric_dev
                poll: true
        jobs: [normal]
        robots: []

    test_repo_2:
        type: git
        url: git@github.com/ipa-fmw/cob_common
        version: fuerte_dev
        poll: true
        ros_distro: [fuerte]
        prio_ubuntu_distro: precise
        prio_arch: amd64
        matrix_distro_arch:
        dependencies:
        jobs: []
        robots: []

