server_name: fmw-xps
user_name: admin
repositories:
  cob_common:
    ros_distro: [groovy, hydro]
    robots: null
    jobs: [regular_build]
    poll: true
    dependencies: {}
    prio_ubuntu_distro: precise
    regular_matrix:
      quantal: [amd64, i386]
      precise: [i386]
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/cob_common.git
    version: groovy_dev
email: fmw@ipa.fhg.de
committer_email_enabled: false
