pipeline_github_url: git@github.com/ipa320/jenkins_pipelines/jenkins_test_server/fmw-jk
user_name: fmw-jk
server_name: jenkins_test_server
email: jannik.kett@gmail.com
committer: 'false'

repositories:
    ros_tutorials:
        type : git
        url: git://github.com/ros/ros_tutorials.git
        version: groovy-devel
        poll: true
        ros_distro: [groovy]
        prio_ubuntu_distro: oneiric
        prio_arch: amd64
        matrix_distro_arch:
        dependencies:
            catkin:
                type: git
                url: git://github.com/ros/catkin.git
                version: groovy-devel
                poll: false
        jobs: []
