pipeline_github_url: git@github.com/ipa320/jenkins_pipelines/jenkins_test_server/fmw-jk
user_name: fmw-jk
server_name: jenkins_test_server
email: jannik.kett@gmail.com
committer: 'false'

repositories:
    ros_tutorials:
        type : git
        url: git://github.com/ros/ros_tutorials.git
        version: groovy-devel
        private: false
        prio_distro_arch:
            groovy:
                ubuntu_distro: oneiric
                arch: amd64
        dependencies:
            catkin:
                type: git
                url: git://github.com/ros/catkin.git
                version: groovy-devel
                private: false
        jobs: []
