server_name: cob-jenkins-server
user_name: ipa320
repositories:
  cob_navigation:
    ros_distro: [groovy]
    robots: []
    jobs: [regular_build]
    poll: true
    dependencies:
      cob_environments: {poll: true, type: git, url: 'git@github.com:ipa320/cob_environments.git',
        version: groovy_dev}
      cob_common: {poll: true, type: git, url: 'git@github.com:ipa320/cob_common.git',
        version: groovy_dev}
    matrix_distro_arch:
      oneiric: [amd64, i386]
      quantal: [amd64, i386]
      precise: [i386]
    prio_ubuntu_distro: precise
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/cob_navigation.git
    version: groovy_dev
email: fmw@ipa.fhg.de
committer_email_enabled: false
