server_name: cob-jenkins-server
user_name: ipa320
repositories:
  cob_navigation:
    ros_distro: [groovy]
    robots: null
    jobs: [regular_build, downstream_build, nongraphics_test, graphics_test]
    poll: true
    dependencies:
      cob_environments: {poll: true, type: git, url: 'git@github.com:ipa320/cob_environments.git',
        version: groovy_dev}
    prio_ubuntu_distro: precise
    regular_matrix:
      oneiric: [amd64, i386]
      quantal: [amd64, i386]
      precise: [i386]
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/cob_navigation.git
    version: groovy_dev
email: fmw@ipa.fhg.de
committer_email_enabled: false
