server_name: cob-jenkins-server
user_name: mig
repositories:
  cob_navigation__fuerte:
    ros_distro: [fuerte]
    robots: []
    jobs: [regular_build]
    poll: true
    dependencies: {}
    matrix_distro_arch:
      oneiric: [amd64, i386]
      precise: [i386]
    prio_ubuntu_distro: precise
    prio_arch: amd64
    type: git
    url: git@github.com:ipa-mig/cob_navigation.git
    version: fuerte_dev
email: Matthias.Gruhler@ipa.fraunhofer.de
committer_email_enabled: false
