server_name: fmw-xps
user_name: fmw
repositories:
  cob_extern:
    ros_distro: [groovy]
    robots: null
    jobs: [regular_build]
    poll: true
    dependencies: {}
    prio_ubuntu_distro: precise
    regular_matrix:
      oneiric: [amd64, i386]
      precise: [i386]
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/cob_extern.git
    version: groovy_dev
email: fmw@ipa.fhg.de
committer_email_enabled: false
