server_name: fmw-xps
user_name: fmw
repositories:
  cob_common__jenkinstest_groovy:
    ros_distro: [groovy]
    robots: null
    jobs: [regular_build, downstream_build, nongraphics_test]
    poll: true
    dependencies: {}
    prio_ubuntu_distro: precise
    regular_matrix:
      oneiric: [amd64, i386]
      quantal: [amd64, i386]
      precise: [i386]
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/cob_common.git
    version: groovy_dev
  cob_common__jenkinstest_hydro:
    ros_distro: [hydro]
    robots: null
    jobs: [regular_build, downstream_build, nongraphics_test]
    poll: true
    dependencies: {}
    prio_ubuntu_distro: precise
    regular_matrix:
      raring: [amd64, i386]
      quantal: [amd64, i386]
      precise: [i386]
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/cob_common.git
    version: hydro_dev
email: fmw@ipa.fhg.de
committer_email_enabled: false
