server_name: jenkins-test-server
user_name: fmw-ak
repositories:
  cob_navigation:
    ros_distro: [groovy]
    robots: [desire]
    jobs: [hardware_build]
    poll: true
    dependencies:
      cob_environments: {poll: false, type: git, url: 'git@github.com:ipa320/cob_environments.git',
        version: groovy_dev}
    prio_ubuntu_distro: precise
    regular_matrix: {}
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/cob_navigation.git
    version: groovy_dev
email: fmw-ak@ipa.fhg.de
committer_email_enabled: false
