server_name: jenkins-test-server
user_name: fmw-ak
repositories:
  cob_extern:
    ros_distro: [groovy]
    robots: [desire]
    jobs: [hardware_build]
    poll: true
    dependencies: {}
    prio_ubuntu_distro: precise
    regular_matrix: {}
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/cob_extern.git
    version: groovy_dev
email: fmw-ak@ipa.fhg.de
committer_email_enabled: false
