server_name: build.care-o-bot.org
user_name: ipa320
repositories:
  cob_simulation__groovy_dev:
    ros_distro: [groovy]
    robots: null
    jobs: [regular_build]
    poll: true
    dependencies:
      universal_robot: {poll: true, type: git, url: 'git@github.com:ipa320/universal_robot.git',
        version: groovy_dev}
      schunk_modular_robotics: {poll: true, type: git, url: 'git@github.com:ipa320/schunk_modular_robotics.git',
        version: groovy_dev}
      cob_environments: {poll: true, type: git, url: 'git@github.com:ipa320/cob_environments.git',
        version: groovy_dev}
      cob_robots: {poll: true, type: git, url: 'git@github.com:ipa320/cob_robots.git',
        version: groovy_dev}
    prio_ubuntu_distro: precise
    regular_matrix:
      oneiric: [amd64, i386]
      quantal: [amd64, i386]
      precise: [i386]
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/cob_simulation.git
    version: groovy_dev
email: fmw@ipa.fhg.de
committer_email_enabled: false
