server_name: build.care-o-bot.org
user_name: jannik
repositories:
  cob_navigation:
    ros_distro: [groovy]
    robots: null
    jobs: [downstream_build, nongraphics_test]
    poll: true
    dependencies:
      cob_environments: {poll: false, type: git, url: 'git@github.com:ipa320/cob_environments.git',
        version: groovy_dev}
    prio_ubuntu_distro: oneiric
    regular_matrix: {}
    prio_arch: i386
    type: git
    url: git@github.com:ipa320/cob_navigation.git
    version: groovy_dev
  cob_extern:
    ros_distro: [groovy]
    robots: null
    jobs: []
    poll: true
    dependencies: {}
    prio_ubuntu_distro: oneiric
    regular_matrix: {}
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/cob_extern.git
    version: groovy_dev
email: jannik.kett@gmail.com
committer_email_enabled: false
