pipeline_github_url: git@github.com/ipa320/jenkins_pipelines/user_name__server_name
pipeline_name: user_name__server_name
#pipeline_type: [build, gazebo, hardware, release] # labels for jobs/nodes and server config
user_name: test_user
server_name: server_name
email: test@ipa.fhg.de
committer: 'false'

repositories:
    test_repo_1:
        type: git  # git, hg, svn
        url: git@github.com/user/repo1
        version: master
        private: 'false'
        ros_distro:
            test_rosdistro:
                ubuntu_distro: natty
                arch: amd64
            test_rosdistro_2:
                ubuntu_distro: oneiric
                arch: amd64
        dependencies:
            dep_repo_1:
                type: git  # git, hg, svn
                url: git@github.com/user_x/dep_repo_1
                version: master
                private: 'true'
        jobs: [normal, sim, db, down, app, hw, release]

    test_repo_2:
        type: git
        url: git@github.com/user/repo2
        version: test
        private: 'false'
        ros_distro:
            test_rosdistro:
                ubuntu_distro: natty
                arch: amd64
        dependencies:
        jobs: []
