server_name: jenkins-test-server
user_name: fmw-jk
repositories:
  cob_driver__abc:
    ros_distro: [electric]
    robots: []
    jobs: [regular_build, hardware_build]
    poll: true
    dependencies:
      cob_common: {poll: false, type: git, url: 'git@github.com:/cob_common.git',
        version: master}
    matrix_distro_arch:
      natty: [i386]
    prio_ubuntu_distro: lucid
    prio_arch: amd64
    type: git
    url: git@github.com:fmw-jk/cob_driver.git
    version: master
email: jannik.kett@gmail.com
committer_email_enabled: false
