server_name: jenkins-test-server
user_name: fmw-jk
repositories:
  ? ''
  : ros_distro: [fuerte]
    robots: []
    jobs: []
    poll: true
    dependencies: {}
    matrix_distro_arch: {}
    prio_ubuntu_distro: lucid
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/.git
    version: master
email: jannik.kett@gmail.com
committer_email_enabled: true
