server_name: jenkins-test-server
user_name: fmw-jk
repositories:
  cob_navigation__rc:
    ros_distro: [electric]
    robots: []
    jobs: [regular_build, downstream_build, nongraphics_test]
    poll: true
    dependencies:
      cob_environments: {poll: false, type: git, url: 'git@github.com:ipa320/cob_environments.git',
        version: electric_release_candidate}
    prio_ubuntu_distro: oneiric
    regular_matrix:
      oneiric: [i386]
      maverick: [i386]
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/cob_navigation.git
    version: electric_release_candidate
email: jannik.kett@gmail.com
committer_email_enabled: false
