server_name: jenkins-test-server
user_name: fmw-jk
repositories:
  cob_extern:
    ros_distro: [electric]
    robots: []
    jobs: [regular_build]
    poll: true
    dependencies: {}
    matrix_distro_arch: {}
    prio_ubuntu_distro: maverick
    prio_arch: amd64
    type: git
    url: git@github.com:fmw-jk/cob_extern.git
    version: electric
email: jannik.kett@gmail.com
committer_email_enabled: false
