pipeline_github_url: git@github.com/ipa320/jenkins_pipelines/jenkins-test-server/fmw-jk
user_name: fmw-jk
user_group: admin
server_name: jenkins-test-server
email: jannik.kett@gmail.com
committer: false

repositories:
    ros_tutorials:
        type: git
        url: git://github.com/ros/ros_tutorials.git
        version: groovy-devel
        poll: true
        ros_distro: [groovy]
        prio_ubuntu_distro: oneiric
        prio_arch: amd64
        matrix_distro_arch:
        dependencies:
        jobs: []
    ros_tutorials__catkin:
        type: git
        url: git://github.com/ros/ros_tutorials.git
        version: groovy-devel
        poll: true
        ros_distro: [groovy]
        prio_ubuntu_distro: oneiric
        prio_arch: amd64
        matrix_distro_arch:
        dependencies:
            catkin:
                type: git
                url: git://github.com/ros/catkin.git
                version: groovy-devel
                poll: true
        jobs: []
    ros_comm:
        type: git
        url: git://github.com/ros/ros_comm.git
        version: groovy-devel
        poll: true
        ros_distro: [groovy]
        prio_ubuntu_distro: oneiric
        prio_arch: amd64
        matrix_distro_arch:
        dependencies:
        jobs: []
    catkin:
        type: git
        url: git://github.com/ros/catkin.git
        version: groovy-devel
        poll: true
        ros_distro: [groovy]
        prio_ubuntu_distro: oneiric
        prio_arch: amd64
        matrix_distro_arch:
            lucid: [i386]
        dependencies:
        jobs: []
    cob_common:
        type: git
        url: git://github.com/ipa320/cob_common.git
        version: master
        poll: true
        ros_distro: [electric]
        prio_ubuntu_distro: oneiric
        prio_arch: amd64
        matrix_distro_arch:
        dependencies:
        jobs: []
