user_name: fmw-jk
user_group: admin
server_name: jenkins-test-server
email: jannik.kett@gmail.com
committer_email_enabled: false

repositories:
    ros_tutorials:
        type: git
        url: git://github.com/ros/ros_tutorials.git
        version: groovy-devel
        poll: true
        ros_distro: [groovy]
        prio_ubuntu_distro: oneiric
        prio_arch: amd64
        matrix_distro_arch:
            oneiric: [i386]
            precise: [amd64, i386]
        dependencies:
        jobs: [normal, down, bringup, highlevel]
        robots: [cob3-3]
    ros_tutorials__catkin:
        type: git
        url: git://github.com/ros/ros_tutorials.git
        version: groovy-devel
        poll: true
        ros_distro: [groovy]
        prio_ubuntu_distro: oneiric
        prio_arch: i386
        matrix_distro_arch:
            oneiric: [amd64]
        dependencies:
            catkin:
                type: git
                url: git://github.com/ros/catkin.git
                version: groovy-devel
                poll: true
        jobs: [normal, down, sim, db, app]
        robots: []
    cob_common__groovy:
        type: git
        url: git://github.com/ipa320/cob_common.git
        version: release_fuerte
        poll: true
        ros_distro: [groovy]
        prio_ubuntu_distro: oneiric
        prio_arch: amd64
        matrix_distro_arch:
        dependencies:
            ros:
                type: git
                url: git://github.com/ros/ros.git
                version: groovy-devel
                poll: false
        jobs: []
        robots: []
    cob_common__fuerte:
        type: git
        url: git://github.com/ipa320/cob_common.git
        version: release_fuerte
        poll: true
        ros_distro: [fuerte]
        prio_ubuntu_distro: oneiric
        prio_arch: amd64
        matrix_distro_arch:
        dependencies:
        jobs: []
        robots: []
    cob_driver:
        type: git
        url: git://github.com/ipa320/cob_driver.git
        version: release_fuerte
        poll: true
        ros_distro: [fuerte]
        prio_ubuntu_distro: oneiric
        prio_arch: amd64
        matrix_distro_arch:
        dependencies:
        jobs: []
        robots: []
#    ros_comm:
#        type: git
#        url: git://github.com/ros/ros_comm.git
#        version: groovy-devel
#        poll: true
#        ros_distro: [groovy]
#        prio_ubuntu_distro: oneiric
#        prio_arch: amd64
#        matrix_distro_arch:
#        dependencies:
#        jobs: []
#        robots: []
    cob_common:
        type: git
        url: git://github.com/ipa320/cob_common.git
        version: master
        poll: true
        ros_distro: [electric]
        prio_ubuntu_distro: natty
        prio_arch: amd64
        matrix_distro_arch:
            lucid: [amd64]
        dependencies:
        jobs: [normal]
        robots: []
    cob_environment_perception:
        type: git
        url: git://github.com/ipa320/cob_environment_perception.git
        version: master
        poll: true
        ros_distro: [electric]
        prio_ubuntu_distro: natty
        prio_arch: amd64
        matrix_distro_arch:
        dependencies:
        jobs: []
        robots: []
    cob_navigation_intern:
        type: git
        url: git@github.com:ipa320/cob_navigation_intern.git
        version: master
        poll: true
        ros_distro: [electric]
        prio_ubuntu_distro: natty
        prio_arch: amd64
        matrix_distro_arch:
        dependencies:
        jobs: []
        robots: []
    baer_automation:
        type: git
        url: git@github.com:ipa320/baer_automation.git
        version: master
        poll: true
        ros_distro: [electric]
        prio_ubuntu_distro: natty
        prio_arch: amd64
        matrix_distro_arch:
        dependencies:
        jobs: []
        robots: []
