server_name: jenkins-test-server
user_name: fmw-jk
repositories:
  cob_navigation_intern:
    ros_distro: [groovy]
    robots: null
    jobs: []
    poll: true
    dependencies: {}
    prio_ubuntu_distro: oneiric
    regular_matrix: {}
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/cob_navigation_intern.git
    version: fuerte_dev
  ba:
    ros_distro: [groovy]
    robots: null
    jobs: [downstream_build, graphics_test]
    poll: true
    dependencies:
      cob_substitute: {poll: false, test: false, type: git, url: 'git@github.com:ipa320/cob_substitute.git',
        version: groovy_dev}
      cob_calibration_data: {poll: false, test: false, type: git, url: 'git@github.com:ipa320/cob_calibration_data.git',
        version: groovy_dev}
      cob_navigation: {poll: false, test: false, type: git, url: 'git@github.com:ipa320/cob_navigation.git',
        version: groovy_dev}
      cob_simulation: {poll: false, test: false, type: git, url: 'git@github.com:ipa320/cob_simulation.git',
        version: groovy_dev}
      universal_robot: {poll: false, test: false, type: git, url: 'git@github.com:ipa320/universal_robot.git',
        version: groovy_dev}
      cob_command_tools: {poll: false, test: false, type: git, url: 'git@github.com:ipa320/cob_command_tools.git',
        version: groovy_dev}
      schunk_modular_robotics: {poll: false, test: false, type: git, url: 'git@github.com:ipa320/schunk_modular_robotics.git',
        version: groovy_dev}
      cob_driver: {poll: false, test: false, type: git, url: 'git@github.com:ipa320/cob_driver.git',
        version: groovy_dev}
      cob_extern: {poll: false, test: false, type: git, url: 'git@github.com:ipa320/cob_extern.git',
        version: groovy_dev}
      cob_environments: {poll: false, test: false, type: git, url: 'git@github.com:ipa320/cob_environments.git',
        version: groovy_dev}
      cob_common: {poll: false, test: false, type: git, url: 'git@github.com:ipa320/cob_common.git',
        version: groovy_dev}
      cob_robots: {poll: false, test: false, type: git, url: 'git@github.com:ipa320/cob_robots.git',
        version: groovy_dev}
    prio_ubuntu_distro: oneiric
    regular_matrix: {}
    prio_arch: amd64
    type: git
    url: git@github.com:fmw-jk/ba.git
    version: groovy
  cob_environments:
    ros_distro: [groovy, hydro]
    robots: desire
    jobs: [hardware_build]
    poll: true
    dependencies: {}
    prio_ubuntu_distro: precise
    regular_matrix: {}
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/cob_environments.git
    version: hydro_dev
  cob_navigation__dev:
    ros_distro: [groovy]
    robots: desire
    jobs: [regular_build, downstream_build, nongraphics_test, hardware_build]
    poll: true
    dependencies:
      cob_environments: {poll: false, test: false, type: git, url: 'git@github.com:ipa320/cob_environments.git',
        version: groovy_dev}
    prio_ubuntu_distro: oneiric
    regular_matrix:
      oneiric: [i386]
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/cob_navigation.git
    version: groovy_dev
email: jannik.kett@gmail.com
committer_email_enabled: false
