server_name: cob-jenkins-server
user_name: goa-tz
repositories:
  cob_people_perception:
    ros_distro: [electric]
    robots: []
    jobs: []
    poll: true
    dependencies:
      cob_perception_common: {poll: false, type: git, url: 'git@github.com:ipa320/cob_perception_common.git',
        version: electric_dev}
    matrix_distro_arch: {}
    prio_ubuntu_distro: natty
    prio_arch: amd64
    type: git
    url: git@github.com:ipa-goa-tz/cob_people_perception.git
    version: experimental
email: thomas.zwoelfer@ipa.fraunhofer.de
committer_email_enabled: false
