server_name: cob-jenkins-server
user_name: nhg
repositories:
  cob_calibration_data:
    ros_distro: [groovy]
    robots: []
    jobs: []
    poll: true
    dependencies: {}
    matrix_distro_arch: {}
    prio_ubuntu_distro: precise
    prio_arch: amd64
    type: git
    url: git@github.com:ipa-nhg/cob_calibration_data.git
    version: groovy_dev
email: nadia.hammoude.garcia@ipa.fraunhofer.de
committer_email_enabled: false
