server_name: localhost
user_name: a
repositories:
  cob_manipulation_sandbox__ueoiaeo:
    ros_distro: [fuerte, groovy]
    robots: [cob3-3, cob3-6]
    jobs: [regular_build, downstream_build, hardware_build, automatic_hw_test, release]
    poll: true
    dependencies:
      cob_industrial: {poll: false, type: git, url: 'git@github.com:ipa320/cob_industrial.git',
        version: master}
    matrix_distro_arch:
      natty: [i386]
      oneiric: [amd64, i386]
      raring: [i386]
      maverick: [amd64]
      quantal: [amd64]
    prio_ubuntu_distro: oneiric
    prio_arch: i386
    type: git
    url: git@github.com:ipa-mdl/cob_manipulation_sandbox.git
    version: master
email: jannik.kett@gmail.com
committer_email_enabled: true
