server_name: localhost
user_name: a
repositories:
  cob_common__dev:
    ros_distro: [electric]
    robots: []
    jobs: [regular_build, downstream_build, nongraphics_test, graphics_test, hardware_build]
    poll: true
    dependencies:
      cob_canopen: {poll: false, type: git, url: 'git@github.com:fmw-jk/cob_canopen.git',
        version: catkin}
    matrix_distro_arch:
      natty: [i386]
      lucid: [amd64, i386]
    prio_ubuntu_distro: oneiric
    prio_arch: amd64
    type: git
    url: git@github.com:fmw-jk/cob_common.git
    version: master
email: jannik.kett@gmail.com
committer_email_enabled: true
