server_name: localhost
user_name: a
repositories:
  ? ''
  : ros_distro: [fuerte]
    robots: []
    jobs: []
    poll: true
    dependencies: {}
    matrix_distro_arch: {}
    prio_ubuntu_distro: lucid
    prio_arch: amd64
    type: git
    url: git@github.com:fmw-jk/.git
    version: master
  __dev:
    ros_distro: [electric]
    robots: []
    jobs: [regular_build, downstream_build, nongraphics_test, graphics_test, hardware_build]
    poll: true
    dependencies:
      ? ''
      : {poll: false, type: git, url: 'git@github.com:fmw-jk/.git', version: catkin}
    matrix_distro_arch:
      natty: [i386]
      lucid: [amd64, i386]
    prio_ubuntu_distro: oneiric
    prio_arch: amd64
    type: git
    url: git@github.com:fmw-jk/.git
    version: master
email: jannik.kett@gmail.com
committer_email_enabled: true
