server_name: jenkins-test-server
user_name: a
repositories:
  cob_driver:
    ros_distro: [fuerte]
    robots: []
    jobs: []
    poll: true
    dependencies: {}
    matrix_distro_arch: {}
    prio_ubuntu_distro: natty
    prio_arch: i386
    type: git
    url: git@github.com:ipa320/cob_driver.git
    version: electric_dev
email: enter your email address here
committer_email_enabled: true
