server_name: localhost
user_name: e
repositories:
  cob_common__aeoae:
    ros_distro: [fuerte, groovy]
    robots: []
    jobs: []
    poll: true
    dependencies:
      cob_bringup_overlays: {poll: true, type: git, url: 'git@github.com:cu-noyvirt/cob_bringup_overlays.git',
        version: master}
      cob_karto: {poll: false, type: git, url: 'git@github.com:ipa-fmw/cob_karto.git',
        version: master}
    matrix_distro_arch: {}
    prio_ubuntu_distro: maverick
    prio_arch: amd64
    type: git
    url: git@github.com:ipa-fmw/cob_common.git
    version: experimentation_days
email: enter your email address here
committer_email_enabled: true
