server_name: cob-jenkins-server
user_name: fmw-ta
repositories:
  ipa_canopen:
    ros_distro: [groovy]
    robots: []
    jobs: [regular_build]
    poll: true
    dependencies: {}
    matrix_distro_arch:
      oneiric: [amd64, i386]
      quantal: [amd64, i386]
      precise: [i386]
    prio_ubuntu_distro: precise
    prio_arch: amd64
    type: git
    url: git@github.com:thiagodefreitas/ipa_canopen.git
    version: groovy_dev
email: thiago.de.freitas.oliveira.araujo@ipa.fraunhofer.de
committer_email_enabled: false
