server_name: cob-jenkins-server
user_name: fmw-ta
repositories:
  cob_driver:
    ros_distro: [groovy]
    robots: []
    jobs: []
    poll: true
    dependencies: {}
    matrix_distro_arch: {}
    prio_ubuntu_distro: oneiric
    prio_arch: amd64
    type: git
    url: git@github.com:thiagodefreitas/cob_driver.git
    version: groovy_dev
email: thiagodefreitas@gmail.com
committer_email_enabled: false
