server_name: cob-jenkins-server
user_name: goa-sf
repositories:
  cob_perception_common:
    ros_distro: [electric]
    robots: []
    jobs: []
    poll: true
    dependencies: {}
    matrix_distro_arch: {}
    prio_ubuntu_distro: natty
    prio_arch: amd64
    type: git
    url: git@github.com:ipa-goa-sf/cob_perception_common.git
    version: electric_dev
  cob_environment_perception:
    ros_distro: [electric, fuerte, groovy]
    robots: []
    jobs: []
    poll: true
    dependencies: {}
    matrix_distro_arch: {}
    prio_ubuntu_distro: oneiric
    prio_arch: amd64
    type: git
    url: git@github.com:ipa-goa-sf/cob_environment_perception.git
    version: master
email: goa-sf@ipa.fraunhofer.de
committer_email_enabled: false
