pipeline_github_url: git@github.com/fmw-jk/jenkins_pipelines/jenkins-test-server/test-user  # git@github.com/ipa320/jenkins_pipelines/server_name/user_name
user_name: test-user
user_group: test-group # admin, release, MA, student
server_name: jenkins-test-server
email: test@ipa.fhg.de
committer: false

repositories:
    test_repo_1:
        type: git  # git, hg, svn
        url: git@github.com/user/repo1
        version: master
        poll: true  # for first level repos always true
        ros_distro: [test_rosdistro, test_rosdistro_2]  # electric, fuerte,...
        prio_ubuntu_distro: oneiric
        prio_arch: amd64
        matrix_distro_arch:
            oneiric: [i386]
            lucid: [amd64, i386]
        dependencies:
            dep_repo_1:
                type: git  # git, hg, svn
                url: git@github.com/user_x/dep_repo_1
                version: master
                poll: true
        jobs: [normal, sim, db, down, app, hw, release]

    test_repo_2:
        type: git
        url: git@github.com/user/repo2
        version: test
        poll: true
        ros_distro: [test_rosdistro]
        prio_ubuntu_distro: natty
        prio_arch: amd64
        matrix_distro_arch:
        dependencies:
            dep_repo_1:
                type: git  # git, hg, svn
                url: git@github.com/user_x/dep_repo_1
                version: master
                poll: true
            dep_repo_2:
                type: git  # git, hg, svn
                url: git@github.com/user_y/dep_repo_2
                version: master
                poll: true
            dep_repo_3:
                type: git  # git, hg, svn
                url: git@github.com/user_y/dep_repo_3
                version: master
                poll: false
            dep_repo_4:
                type: hg  # git, hg, svn
                url: https://kforge.ros.org/test/dep_repo_4
                version: master
                poll: true
            dep_repo_5:
                type: svn  # git, hg, svn
                url: https://code.test.org/svn/test/stacks/dep_repo_5
                version:
                poll: true
        jobs: []
